### ISSUE TITLE
Add button to date picker dropdown 

### ISSUE THREAD

**Issue by courtneybradford** [TelegraphCreative/bottle-dashboard-fed#5]
Please add a small outline button (as wide as the calendar’s div), centered below the calendar in date picker dropdown.

**Comment by SoldierCorp** [comment]
Like this @courtneybradford ?

![image](https://user-images.githubusercontent.com/1775881/53534897-4d84df80-3ac6-11e9-996a-ed85656ea856.png)

**Comment by courtneybradford** [comment]
Yes, but please use an outline button instead of primary style. Thanks!
